/home/jmayorgab/2025_I_IntroSciCompHPC_JJM/2025-07-04/graphs.py:5: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv("parallel_results_slurm.txt", delim_whitespace=True)
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Threads'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jmayorgab/2025_I_IntroSciCompHPC_JJM/2025-07-04/graphs.py", line 8, in <module>
    tiempos_base = df[df["Threads"] == 1].set_index("Modo")["Tiempo(s)"].to_dict()
                      ~~^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Threads'
